### ISSUE TITLE
как этой хуйней пользоваться дурак

### ISSUE THREAD

**Issue by woidzero** [D31LtheFOX/GDPSLaunch#1]
дурачек блять как это юзать блятб **отвечай**

**Comment by RenslyIsFound** [comment]
дурачек блять как это юзать блятб **отвечай**

**Comment by litecave** [comment]
иди нахуй ринсли, открывай бляттт через девелнехст проект и всё будет норм блятб
и жди до релиза, я разбираюсь с кнопкой установить дурачек...
